### ISSUE TITLE
kate: textDocument/signatureHelp unhandled

### ISSUE THREAD

**Issue by hololeap** [haskell/haskell-language-server#1262]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /usr/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		Not found
ghc:		8.10.3
```
Which lsp-client do you use:

[kate-20.08.3](https://docs.kde.org/trunk5/en/applications/kate/kate-application-plugin-lspclient.html)

Describe your project (alternative: link to the project):

A simple test `.hs` file in `/tmp`

Contents of `hie.yaml`:
_Not present_

### Steps to reproduce

I have been seeing this error show up in my Messages tab under the LSP status window

### Expected behaviour

No error message

### Actual behaviour

`haskell-language-server` seems to be working overall.

But, I get non-fatal errors like this repeatedly. I assume this is because `file://` URIs are not supported:

### Include debug information

```
[2021-01-25T18:32:50] [Error] [LSP Server: haskell@/home/kinetik]
haskell-lsp:no handler for. Object (fromList [("jsonrpc",String "2.0"),("params",Object (fromList [("textDocument",Object (fromList [("uri",String "file:///tmp/foo.hs")])),("position",Object (fromList [("line",Number 1.0),("character",Number 14.0)]))])),("method",String "textDocument/signatureHelp"),("id",Number 306.0)])
```

**Comment by Ailrun** [comment]
I'm failed to start HLS in Kate: How did you succeed?
BTW, your root directory (`[LSP Server: haskell@/home/kinetik]`) looks not valid, it should be `/tmp`, I believe.

**Comment by hololeap** [comment]
@Ailrun You have to:

1. Enable `LSP Client` in the plugins (under `Configure Kate...`)
2. A new entry called `LSP Client` will appear in the configuration settings. In there, go to the `User Server Settings` tab and make the Haskell entry look like this:
```
        "haskell": {
            "command": ["haskell-language-server-wrapper", "--lsp"],
            "rootIndicationFileNames": ["*.cabal", "stack.yaml", "cabal.project", "package.yaml"],
            "url": "https://github.com/haskell/haskell-language-server",
            "highlightingModeRegex": "^Haskell$"
        },
```

I submitted a PR to the KDE people to have this default changed in later releases.

**Comment by Ailrun** [comment]
Oh, right, I forgot to add `"--lsp"` option. Let me try to reproduce it again.

**Comment by Ailrun** [comment]
It looks like HLS works well, and I cannot reproduce such an error. Maybe some latest commits of HLS or Kate has fixed problems?

**Comment by hololeap** [comment]
@Ailrun What version of HLS did you test with? I can also try a newer version of kate.

**Comment by Ailrun** [comment]
@hololeap Mine is the version built from the latest commit with stack (so the other versions are all fixed by stack.yaml)

**Comment by hololeap** [comment]
@Ailrun Thanks I will try that out.

**Comment by hololeap** [comment]
I built the latest `haskell-language-server`, `ghcide`, and plugins from the latest commit (using Gentoo, not stack), and updated to kate 20.12.1 and I'm still getting these messages. I tried starting kate in my project folder.

**Comment by jneira** [comment]
@hololeap there is no a canonical one, you can check a list of editors that are known to work with hls though: https://github.com/haskell/haskell-language-server#configuring-your-editor

But it seems @Ailrun has been able to use hls with kate so there has to be some difference between your envs that can help to discover the cause of the error

**Comment by hololeap** [comment]
I found the string `"haskell-lsp:no handler for."` in `haskell-lsp-0.23.0.0` so perhaps I should file a bug report there, although it may be fixed in version 0.24.0.0. Are there plans to support the latest version of `haskell-lsp`?

Since I am using Gentoo instead of stack, there are likely a number of differences in terms of dependency versions between my environment and @Ailrun's. That is likely where the discrepancy lies. I can try building the latest source using stack and see if there is any difference.

**Comment by wz1000** [comment]
The problem isn't URIs, its that HLS/ghcide don't define a handler for the `textDocument/signatureHelp` request. Maybe you can configure your editor to not send this request? Or, as the error is non-fatal (at least it should be, please change your bug report to focus on this fact if it is not), you can just ignore it?

As such, I don't think this is a bug report, more of a feature request.

**Comment by hololeap** [comment]
@wz1000 Thanks for the info. FWIW I did mention that it was a non-fatal error. I can easily ignore this error, but I thought it was worth bringing up.

**Comment by Ailrun** [comment]
Yeah, weirdly I didn't get any error like that. Maybe because I don't use kate so there's no plugins other than LSP?

**Comment by wz1000** [comment]
> Edit: `haskell-lsp-0.23.0.0` [seems to support this request](https://github.com/alanz/lsp/blob/master/test/MethodSpec.hs#L44). Is this relevant?

There is no bug in `haskell-lsp`, it supports the request just fine. Its just that we haven't implemented the request in ghcide or HLS.

**Comment by jneira** [comment]
@hololeap have you got the chance of trying with a newer hls version (1.5.1)?
There were some changed about type  signatures (and the request is about that I hope)

**Comment by michaelpj** [comment]
I'm pretty sure that as @wz1000 says we just don't implement a handler for `signatureHelp`. I'm pretty sure that the server capabilities should say that there is no signature help provider, so IMO this is a bug in the client (kate) if it's asking the server for something that the server has said it doesn't provide.

**Comment by hololeap** [comment]
This error message is gone with my current setup, which is `ghc-8.10.6`, `hls-1.5.1.0` and `kate` built from the latest source. I have no idea when it stopped. I actually forgot I opened this bug.
