### ISSUE TITLE
Program error: Failed to load interface for ‘Main’ no unit id matching ‘main’ was found

### ISSUE THREAD

**Issue by xwvvvvwx** [haskell/haskell-language-server#204]
I have this error in the main executable file in a two projects ([`hevm`](https://github.com/dapphub/dapptools/tree/master/src/hevm), and [`act`](https://github.com/ethereum/act/)).

In both of these projects `haskell-language-server` works very well (type checking / doc lookup / jump to definition) in all files except the main executable (`Main.hs` in `act` and `hevm-cli.hs` in `hevm`).

`cabal new-build` works without errors in both projects.

I am using a globally installed version of `hakell-language-server` built against `ghc8.6.5` using the nix deritvations [here](https://github.com/poscat0x04/hls-nix).

The full output from running `haskell-language-server` from the root of the `act` repo is [here](https://ipfs.io/ipfs/QmefNZYw7b3PyRsYMBZsFr33F6yFRaNBtMzU8kS9KFme6U/out.log).

If you want to reproduce the issue locally, it's probably easiest to use the `act` project. The `shell.nix` in the repo root can be used to prepare a working build environment, but does not currently include an installation of `haskell-language-server` itself.

**Comment by xwvvvvwx** [comment]
The issue was missing `module Main where` declarations. Seems obvious in retrospect although it is quite confusing that `cabal` doesn't seem to need them.

**Comment by fendor** [comment]
Hey! I have encountered the same issue, the reason is GHC will auto-insert the module declaration (if it missing) and add Main.hs to the unit `main`. Then it looks up the unit, and can't find it, hence the error.
I say we keep this issue open because it should not fail with this error message since `cabal` accepts it.

Earlier today, I actually looked into your repo's since I had the suspicion regarding module declarations but in the linked repo, the module declaration was present. Did you change that locally or something?

**Comment by xwvvvvwx** [comment]
I added the `module Main where` declarations [yesterday](https://github.com/ethereum/act/pull/31/files)

**Comment by jneira** [comment]
I cant reproduce with lastest hls and a Main module without the header, @xwvvvvwx could you confirm it it is fixed for you too?

**Comment by xwvvvvwx** [comment]
I can still reproduce with `haskell-language-server` `0.4.0.0` from `nixpkgs`.

**Comment by jneira** [comment]
Thanks for checking it again, it is possible that the os could be related (i am on windows) but i assumed that it should not be.
@fendor could that make sense?

**Comment by fendor** [comment]
No, it is close to impossible that the OS is related. I will check if I can still reproduce it and if it is actually what I think it is.

**Comment by jneira** [comment]
I've just double check it with ghc-8.10.1 (my previous test was with ghc-8.8.3), a main module without the header:

![imagen](https://user-images.githubusercontent.com/54035/94192507-55c61c00-feaf-11ea-810d-51fd431a10bc.png)


No error in the log.

**Comment by jneira** [comment]
@fendor did you have the opportunity of checking if it is reproduced?

**Comment by fendor** [comment]
I can't reproduce it anymore and furthermore, I would expect https://github.com/haskell/haskell-language-server/pull/1435 fixes it for good, too.

**Comment by jneira** [comment]
@fendor nice, thanks for confirming it
@xwvvvvwx feel freeto reopen if you continue experienced the issue
