### ISSUE TITLE
`hls-1.8.0.0` is broken on Ubuntu 20.04 due to missing GLIBC_2.34

### ISSUE THREAD

**Issue by agustinmista** [haskell/haskell-language-server#3160]
Hi! 

The latest release seems to be broken for me on Ubuntu 20.04:

```
[Error - 5:07:07 PM] Connection to server is erroring. Shutting down server.
/home/agustin/.ghcup/tmp/ghcup-ghc-8.10.7_cabal-3.6.2.0_hls-1.8.0.0_stack-2.7.5/haskell-language-server-wrapper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/agustin/.ghcup/tmp/ghcup-ghc-8.10.7_cabal-3.6.2.0_hls-1.8.0.0_stack-2.7.5/haskell-language-server-wrapper)
```

For reference, here is the current version of GLIBC shipped with Ubuntu 20.04:

```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

This happened today after VSCode (forcibly) asked me to update it to `1.8.0.0`. 

In the meantime, I managed to circumvent the problem in VSCode by reverting HLS back to `1.7.0.0` in the `settings.json` file:

```
    "haskell.toolchain": {
      "hls" : "1.7.0.0"
    }
```

**Comment by adlaika** [comment]
Not sure if helpful, but: I'm on Pop!_OS 22.04 LTS, which is derivative of Ubuntu, and it's working fine for me. 

My GLIBC is > 2.34, though:

```$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
```

**Comment by pepeiborra** [comment]
Ubuntu is getting the fedora 33 binary now, we probably need to change that. 

There are binaries for other distros here: https://downloads.haskell.org/~hls/haskell-language-server-1.8.0.0/

Can you let me know which is the most recent binary that works in your system?

**Comment by lsmor** [comment]
I can confirm this is the case. Actually, I commented this same issue in the [Haskell discourse](https://discourse.haskell.org/t/ann-haskell-language-server-1-8-0-0-released/5053/9) thread. In Ubuntu `hls-1.7.0.0` works fine, which up to ghcup-metada uses the fedora27 binary. I don't know if this is a ghcup problem or hls... who is responsable for the ghcup-metada.yaml file?

Also I've check installing debian version of `hls-1.8.0` with `ghcup` using the command 
```
ghcup install hls -u https://downloads.haskell.org/~hls/haskell-language-server-1.8.0.0/haskell-language-server-1.8.0.0-x86_64-linux-deb10.tar.xz 1.8.0.0
``` 

This actually makes `hls` to work again. Not the optimal solution, but a workaround.

**Comment by lucascolley** [comment]
yeah ghcup still thinks hls-1.7.0.0 is the latest version. here is the output of ghcup list
![image](https://user-images.githubusercontent.com/51488791/190265457-a0aa6902-62d6-4642-9ac3-6104ac5a1aaa.png)

**Comment by konn** [comment]
It fails on my Ubuntu 20.04.4 environment seems, too.
Forcing GHCup to reinstall HLS 1.8 for Debian 10 makes GLIBC error disappear, but it didn't work with GHC 9.0.2 installed by stack, due to ABI mismatch. While ago, I had followed [the instruction](https://github.com/haskell/vscode-haskell#ghc-abis-dont-match) to install GHC 9.0.2 binary for Fedora 27, but it seems that this time the binary contradicts the HLS binary for Debian 10 HLS binary.
I've already tested `https://downloads.haskell.org/ghc/9.0.2/ghc-9.0.2-x86_64-deb10-linux.tar.xz` but it still contradicts the ABI of HLS 1.8.0 debian 10 binary as for ghc-boot and array.

**Comment by hasufell** [comment]
Ubuntu has been fixed: https://github.com/haskell/ghcup-metadata/commit/cea865595a748aa697720b09a35f5c4c9210955a

Bindists are unofficial: https://downloads.haskell.org/~ghcup/unofficial-bindists/haskell-language-server/1.8.0.0/

CI run: https://github.com/haskell/ghcup-metadata/actions/runs/3066752966

----

To fix your existing installation run this:

```sh
ghcup rm hls 1.8.0.0
ghcup install hls 1.8.0.0
```

**Comment by decapo01** [comment]
> Ubuntu has been fixed: [haskell/ghcup-metadata@cea8655](https://github.com/haskell/ghcup-metadata/commit/cea865595a748aa697720b09a35f5c4c9210955a)
> 
> Bindists are unofficial: https://downloads.haskell.org/~ghcup/unofficial-bindists/haskell-language-server/1.8.0.0/
> 
> CI run: https://github.com/haskell/ghcup-metadata/actions/runs/3066752966
> 
> To fix your existing installation run this:
> 
> ```shell
> ghcup rm hls 1.8.0.0
> ghcup install hls 1.8.0.0
> ```

I'm still getting this error after reinstalling hls with this procedure.  I'm on Pop!_OS 20.04 LTS.  With the ldd output here
```sh
» ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

**Comment by hasufell** [comment]
PopOS is not Ubuntu and not explicitly supported by ghcup. That means we fall back to `Linux Unknown`, which picks the fedora bindists.

Open a new issue.
