### ISSUE TITLE
How do you use (un)folding?

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#418]
For this single file, with an implicit cradle
```haskell
x = 3

y = x
```
These code actions on `x`
```
  refactor.extract: Fold x in current file
  refactor.extract: Fold x
  refactor.inline: Unfold x in current file
  refactor.inline: Unfold x
```
appear to not do anything.

Am I supposed to also install a `retrie` binary or something similar? I'm using `LanguageClient-neovim`.

**Comment by pepeiborra** [comment]
No need for a retrie binary, if the file typechecks it should rewrite to y=3. There may be a bug where the rewrite uses the file on disk, so you may need to save it first.

**Comment by googleson78** [comment]
It is saved. Does this log help?
[hls-log.txt](https://github.com/haskell/haskell-language-server/files/5252583/hls-log.txt)
It seems to be some path related issue?
```
2020-09-20 23:48:44.036543404 [ThreadId 5] - ---> {"jsonrpc":"2.0","error":{"code":-32603,"message":"invalid value: string \"/tmp/asdf.hs\", expected relative URL without a base"},"id":2}
2020-09-20 23:48:44.036704076 [ThreadId 5] - haskell-lsp:Got reply message:"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"invalid value: string \\\"/tmp/asdf.hs\\\", expected relative URL without a base\"},\"id\":2}"
```

**Comment by pepeiborra** [comment]
Yes, that helps.
I have pushed a potential fix to https://github.com/haskell/haskell-language-server/pull/408
Please test and let me know

**Comment by googleson78** [comment]
Still doesn't work
Version (hash matches that of the branch):
```
blademaster :: /tmp » haskell-language-server --version
haskell-language-server version: 0.4.0.0 (GHC: 8.6.5) (PATH: /home/googleson78/.local/bin/haskell-language-server) (GIT hash: e233ad5c10ca8de4c2624167104b6d9d297b1c8e)
```

Log again - https://gist.github.com/googleson78/b5e811e3351b1459f58c37338d9925ff

**Comment by pepeiborra** [comment]
I've pushed another fix, give it another go when you can.

**Comment by googleson78** [comment]
Do you mean from master? Trying from current master (e390da54a90f2c6c02ce836a27f2d4c33a71f607) gives the same error in the log.

**Comment by pepeiborra** [comment]
#424

**Comment by googleson78** [comment]
Thanks, works from that branch!
