### ISSUE TITLE
Error when using GHC type-checker plugins.

### ISSUE THREAD

**Issue by chfin** [haskell/haskell-language-server#4742]
When using GHC type-checker plugins (`ghc-typelits-knownnat` and `ghc-typelits-natnormalize`), HLS reports errors. In the editor, the error
```
Unexpected usage error
The name Plugin is not in the type environment: are you sure it exists?
```
is shown. When running hls on the command line, the error
```
Program error: Failed to load interface for ‘GHC.Driver.Plugins’.
  no unit id matching ‘ghc-9.10.3-415c’ was found
```
is reported for the file using the plugins.

### Your environment

Which OS do you use?
Arch Linux

Which version of GHC do you use and how did you install it?
9.10.3 with stack

How is your project built (alternative: link to the project)?
stack. Link to minimal project: https://github.com/chfin/ghc-plugins-hls-bug

Which LSP client (editor/plugin) do you use?
Emacs with lsp-mode, error also appears when using HLS on command line

Which version of HLS do you use and how did you install it?
2.12.0.0 compiled for ghc-9.10.3 with ghcup

Have you configured HLS in any way (especially: a `hie.yaml` file)?
no

### Steps to reproduce

- clone https://github.com/chfin/ghc-plugins-hls-bug
- build the project using `stack build`
- run `haskell-language-server-wrapper` or open `src/Lib.hs` in an editor

### Expected behaviour

HLS should build the project without issues and show no error in the file.

### Actual behaviour

When opening `src/Lib.hs`, the editor shows an error message at the top of the file: 
```
Unexpected usage error
The name Plugin is not in the type environment: are you sure it exists?
```

HLS reports the following error on `src/Lib.hs`:
```
2025-10-20T11:32:38.714246Z | Info | updateFileDiagnostics published different from new diagnostics - file diagnostics: File:     <unknown>
Hidden:   no
Range:    1:1-2:1
Source:   pragmas
Severity: DiagnosticSeverity_Error
Code:     <none>
Message:
  Program error: Failed to load interface for ‘GHC.Driver.Plugins’.
  no unit id matching ‘ghc-9.10.3-415c’ was found
```

### Debug information

```
haskell-language-server-wrapper --probe-tools
haskell-language-server version: 2.12.0.0 (GHC: 9.10.3) (PATH: /home/chfin/.ghcup/bin/haskell-language-server-wrapper-2.12.0.0)
Tool versions found on the $PATH
cabal:          3.16.0.0
stack:          3.7.1
ghc:            9.10.3

Tool versions in your project
2025-10-20T11:37:17.537410Z | Debug | stack --stack-yaml /home/chfin/dateien/dev/haskell/playgrounds/ghc-plugins-lsp-test/stack.yaml setup --silent
2025-10-20T11:37:17.879521Z | Debug | stack --stack-yaml /home/chfin/dateien/dev/haskell/playgrounds/ghc-plugins-lsp-test/stack.yaml exec ghc -- --numeric-version
ghc:            9.10.3
```

**Comment by chfin** [comment]
Looks like a somewhat similar error is described in #3297, not sure if that's related.

**Comment by fendor** [comment]
I have to check whether this is still open in 2.13.0.0 or fixed with one of the ghc plugin fixes we merged in the last months.

**Comment by fendor** [comment]
Should be fixed in HLS 2.13.0.0

<img width="2443" height="827" alt="Image" src="https://github.com/user-attachments/assets/23994ad1-d100-446c-962e-adada7aceb40" />

**Comment by chfin** [comment]
Mh, I just installed HLS 2.13.0.0 and I still get exactly the same error.

I installed the 2.13.0.0 via `ghcup compile` since the precompiled version wouldn't run at all, complaining about "GHC ABIs don't match!"

**Comment by fendor** [comment]
You are describing two errors, one for the cli and one for the LSP mode.

I was able only abel to reproduce this issue: 

```
2026-01-27T08:23:30.210710Z | Info | updateFileDiagnostics published different from new diagnostics - file diagnostics: File:     /home/hugin/Documents/haskell/ghc-plugins-hls-bug/src/Lib.hs
Hidden:   no
Range:    1:1-2:1
Source:   compiler
Severity: DiagnosticSeverity_Error
Code:     <none>
Message: 
  (GhcSession,NormalizedFilePath
  "/home/hugin/Documents/haskell/ghc-plugins-hls-bug/src/Lib.hs")cannot satisfy -package
  ghc-plugins-lsp-test-0.1.0.0
  (use -v for more information)
```

This was fixed by running `stack build` beforehand, and then the following invocation worked:

```bash
$ ghcup run --ghc 9.10.3 --cabal 3.16.0.0 -- haskell-language-server-9.10.3 --debug .
```

To make sure we have matching environments.

I guess the question is, how have you installed stack? Do you have installed the stack ghcup integration hook https://www.haskell.org/ghcup/guide/#stack-integration ? This is a requirement to use the HLS compiled via `ghcup compile`.

If you use ghcup, have you ever installed from a different distribution channel?

Also, don't mix ghcup and arch linux provided binaries, have you perhaps ever installed ghc via pacman?

You should run via `HLS_WRAPPER_DEBUG=1 haskell-language-server-...` to give us a more informative error message.

**Comment by chfin** [comment]
Aaaah, it was was the stack-ghcup integration. I had stack installed via ghcup, but I missed the ghc-install.sh hook thing. I thought that the ghcup version of stack was already configured correctly out of the box. Thanks for the help!

What's interesting is that HLS works with the stack-managed GHC without issue when not using GHC plugins.

**Comment by fendor** [comment]
>  What's interesting is that HLS works with the stack-managed GHC without issue when not using GHC plugins.

ABIs can be very confusing :) using GHC plugins could cause other parts of the system to be loaded that actually have an ABI mismatch, or forcing a specific compilation mode... E.g., the external interpreter

**Comment by chfin** [comment]
Yes, that makes sense. It might be a good idea to note somewhere that HLS+stack requires this hook to work correctly. I don't see it mentioned in the installation guide.
